### ISSUE TITLE
Do we should pay for the wiring diagram?

### ISSUE THREAD

**Issue by AlexanderZhang11** [BCN3D/BCN3D-Moveo#13] opened 2016-10-10 02:06 UTC
I cannot find the wiring diagram in the resource list. I am puzzled by the problem of wiring. So does it mean we should pay for this diagram?

**Comment by MarcusWolschon** [comment] 2016-12-15 12:55
Is this a duplicate of
Wiring Diamgram is missed #6
?

**Comment by kitusmark** [comment] 2017-02-02 16:44
Duplicate on #6

**Closed as completed by kitusmark** 2017-02-02 16:44 UTC

**Comment by MohammedAhamed** [comment] 2017-06-11 14:39
I run the project  as graduation project  with some modifications   if any one want help   connect to me  for free  by email  mo.ah.has2014@gmail.com
